name: Release

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    branches:
      - main
      - beta
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_CHART_RELEASER_TOKEN }}
        run: |-
          #!/bin/bash
          set -e
          # optional install steps of semantic-release plugins
          # npm install @semantic-release/exec @semantic-release/git @edgefarm/semantic-release-helm-oci -D
          npx -c semantic-release
